### ISSUE TITLE
Paragraphs

### ISSUE THREAD

**Issue by vr8hub** [irontigran/sun-tzu_the-art-of-war_lionel-giles#67]
This is opening a can of worms, I know. But removing the paragraph numbers has some rippling effects.
1. There are paragraphs that are marked with two numbers, e.g. 5-6 in Chapter 1 (the _Moral Law_) and 13-14 in Chapter 2 and so on. That's a problem for any references to paragraphs in that chapter following those paragraphs, because it means the counts are off. Thus, if there's a reference to paragraph 8 in Chapter 1, the reader will go to the wrong chapter, because they don't know that paragraph 6 was "skipped." Thus, any references to paragraphs including and after the "skipped" one should be reduced by 1. For example, references to Chapter 1 § 6 should be Chapter 1 § 5, since it's the 5th paragraph that contains the text being referred to.
2. This causes more problems with instances of numbered lists, because sometimes those numbered lists are separate paragraphs and sometimes they're not. For example, in chapter 1, the list on paragraph 13 is part of that paragraph. However, in chapter 3, the list starting after paragraph 12 are each their own paragraph. Again, the reader has no way to tell they're different, so references to those (or following) paragraphs are going to send her to the wrong one. _A_ way to solve this might be to use `ol` for the ones that are part of the previous paragraph (like the one in chapter 1), and just use regular paragraphs (with numbers) for the other ones. That way it's clear they're still separate paragraphs. But I don't know what Alex would think about that.
3. Also because of that, we really need something similar to the new "continued" class for paragraphs following blockquotes that should not be indented, vs normal paragraphs following blockquotes that _are_ indented. For example, paragraph 14 that follows the list in chapter 1 isn't indented; that makes it look like a continuation of the list which is itself a continuation of chapter 13. It should be indented to make it clear it's starting a new paragraph. However, for the list following paragraph 17 in chapter 3, the "Victory lies in the knowledge of these five points" _is_ part of the previous paragraph, and thus should not be indented.

As I said, a can of worms. :) To me, this is a text and commentary _on_ the text in one, so having the paragraph numbers makes sense. But, if we're _not_ going to have the paragraph numbers, then we have to adjust the references, etc. to that new reality. (And I certainly don't want to get rid of the paragraph references.)
Another option is to turn every reference to a paragraph into a link; the link would go to the right place even if counting the paragraphs wouldn't get you there. The problem with that is that all of these references are in the endnotes, and we already know that there's no support for links in an endnote. So the link would be there, but there's no reader that can use them. That's not going to help the reader get to the right place.

**Comment by irontigran** [comment]
I'm going to guess that Alex is going to say we should turn paragraph/section references into links, but I'll pose the question in an email.

**Comment by acabal** [comment]
I wonder why some paragraphs have two numbers, like chapter 1-5,6. Why would a single paragraph get two numbers in this case? Does he refer to both numbers separately on different occasions, and the reader is supposed to figure out what part of the sentence he's referring to? If he's referring to parts of a sentence, we can wrap that in `<span>` with an `id` attribute so we can link directly to the part of the sentence if necessary.

In the case of `<ol>`, we can simply send the reader to the paragraph before the `<ol>` if the `<ol>` is semantically part of that paragraph. The block-level separation of `<ol>` is just an artifact of how HTML is written; it's not a big deal to just point to the previous `<p>` if that's what the text really means.

You're right that we'll need to update `core.css` to follow the new `<blockquote>` style indentation for `<ol>` and `<ul>`; I've updated master so this will be in the next version of the tools. If you want, you can pull in the latest core.css from the tools repo and work on this book based on that, and ignore the lint errors which will go away with the next tools version.

We should definitely directly link each reference. I assumed this was already being done. That's one of the big wins of hypertext! :) We can simply replace the text with something like "see here" instead of "see chapter 1 section 8". This is not unlike what we would do if the book referenced page numbers instead of section numbers and pretty much all of our books with extensive commentary do this.

Does that cover it all?

**Comment by vr8hub** [comment]
Jacob may be able to answer why a paragraph has two numbers; I couldn't see any distinguishing characteristic of the ones that have two. Giles definitely refers to those paragraphs, and sometimes by the second number. But (usually?) not to the text itself, just the number, so "See Chapter 1 § 5" and "See Chapter 1 § 6" are functionally equivalent.

Yes, the problem with the `<ol>`s aren't the ones that _are_ part of the previous paragraphs, but the ones that _aren't_. As I mentioned above, the list after paragraph 13 in Chapter 3 are each their own paragraph. Would he just put id's on the individual `<li>` elements and link to them directly? And if so, what would the id's be, since there are multiple <ol> elements in some chapters? E.g., would he count the `<li>`'s in total, across `<ol>`s, so that if the first `<ol>` had five `<li>`s, the first `<li>` of the second `<ol>` would be li-6?

**Comment by acabal** [comment]
> Would he just put id's on the individual `<li>` elements and link to them directly? And if so, what would the id's be, since there are multiple 

Yes, if it's referring to a specific `<li>` then you can put an `id` on it and refer to it directly. The id would be `li-N` with N being its position in the document, not its position in its parent `<ol>`.

**Comment by irontigran** [comment]
Why two numbers: Giles mentions that he generally follows a Chinese commentator's (Sun Hsing-yen) divisions. I assume he thought his translation couldn't be split into the two paragraphs Sun Hsing-yen specifies while maintaining intelligibility.

The chapter references are directly linked, though I didn't change most of the "Chapter VII, section 24" verbiage. I think we're most concerned about the links inevitably not working and the reader not having a way to find the section manually.

Right now I'm thinking that I should carefully review the verbiage of the various references. Saying "see here" doesn't help the reader if the link doesn't work (or if the e-reader can display the entire chapter on one page, as Calibre on my laptop does). But "Chapter VII, section 24" is inaccurate. Perhaps a short quotation of the text would help? For example: "See Chapter VII, 'Gongs and drums...'"

I'll need to correct links that refer to various lists so they point to either the preceding `<p>` or the correct `<li>`, as you guys describe.

**Comment by vr8hub** [comment]
(I'll say again that this would be a whole lot easier, and I think make a better production, if we left the paragraph numbers. We did it in Suetonius, e.g.)

My thoughts are leave the verbiage, or at the most remove the paragraph number ("See here in chapter V"). The links work if they go to the endnotes directly instead of through the popups, and they _sometimes_ work from the popup, depending on the reader (software).

But Alex's thoughts are official. :)

**Comment by acabal** [comment]
Some philosophy: generally we don't want to submit a production that is hobbled by catering to whatever the current state of ereaders is. The idea is that what's in the repo is a "canonical" version for a "perfect" ereader. So, while *today's* ereaders might not all support links from endnotes, that doesn't mean that *tomorrow's* might not; and if no books do it, then support will never materialize. So we always aim for what is technically correct, even if that means today's support might not be stellar. Many ereader projects, like Calibre or Foliate, are very open to feature requests like this; so it might even be as easy as asking the maintainer for support, in order to make it happen.

I get it that it would be easier to keep the numbers. But I think that makes for a poorer reading experience for the average reader. It's not smooth, and for someone who isn't reading the endnotes, they appear redundant and confusingly pointless. They make it *really seem* like you're reading something scholarly, which to some readers can be a turn-off: scholarly things can seem inaccessible. To be perfectly honest, I think for the average English-speaking reader many of these endnotes are going to be too erudite and specialized to engage in meaningfully anyway. That doesn't mean they aren't worth keeping, just that we should consider our target audience as we make these new editions.

Many modern translations (like Kaufman, Ames, or Sawyer to name three) omit numbering and manage the commentary just fine.

We can certainly keep the text as "See Chapter N section X" if you want. Though without numbers I don't think that is much more helpful than "see here". @irontigran do you have a strong opinion on the matter of numbers or no numbers?

**Comment by vr8hub** [comment]
In your first paragraph, you're not worried about the poorer reading experience of the reader. In the second paragraph you are. But the first problem literally prevents the reader from reading the notes, while the second not only doesn't prevent the reader from doing anything, but it _helps_ them with the reading of the material as written. It's not difficult to produce a book that is both readable now, and easy to convert when and if support ever comes. We're penalizing readers for not living in 2025 with no good reason to do so.

There are 600 notes on 35 pages of text (plus another 175 on the various introductions). He mingles comments from 11 different commentators as well as his own. This _is_ a "scholarly" edition of the book, whatever that means. You don't read Giles if the only thing you want to do is read _Art of War_. You read Giles because you want what he brings to _Art of War_. And we're weakening what he brings, and making it more difficult for the reader to get to it. _That_, IMO, is a "poorer reading experience".

But, this is Jacob's production. What I think about it is unimportant. I'm merely offering my perspective, as much on the bigger issue as on this production in particular.

**Comment by acabal** [comment]
> You don't read Giles if the only thing you want to do is read Art of War. You read Giles because you want what he brings to Art of War.

Not in this case; 95% of people are reading these editions because they're free, and the fact that it's Giles is a coincidence. If an actual scholar wants Giles for Giles then it's easy to find a literal edition just about anywhere including print and online. But literal transcription is not the goal of SE. It's thoughtful and accessible editions for modern average readers.

**Comment by irontigran** [comment]
I have a hard time with changing the text from the original, but as you pointed out, we are creating a new edition aimed towards the relatively average modern reader

Attempting to embrace that philosophy, removing the numbers seems like the correct way to go, **but** removing the numbers makes the paragraph divisions seem very choppy - most paragraphs end up being no more than a sentence or two. Following this change all the way to its natural conclusion implies to me that we should merge a good chunk of the paragraphs together and replace section numbers in cross-references with a different way of pointing to the referenced sentence (I still like the short quote idea).

**Comment by acabal** [comment]
I would not merge the paragraphs; that's going past the concept of rearranging content *outside* of the text (i.e. numbering, endnotes, commentary, etc.), and rearranging the text itself wholesale. We rarely if ever want to go that far without really good reason.

Let's go with your idea of replacing number references with just the first few words of the sentence. I think that's a good middle ground and definitely more useful than leaving the numbers in the references but removing them from the text.

**Comment by irontigran** [comment]
I've started replacing number references with the first few words - it seems to be mostly working well, but there are a couple of awkward instances.

In particular, there are a couple notes (69, 71, and 92) which are long lists of section numbers. It seems far too busy to just directly replace the numbers with quotes, in particular note 69, where the list repeats itself and doesn't seem to follow a specific order. I could try making them into a proper list (`<ul>`)?

**Comment by acabal** [comment]
Sure, `<ul>` would work and would certainly be more readable than the original anyway.

**Comment by irontigran** [comment]
Back to note 69 - it's long list of references to the main text that are in no particular order and some are repeated. Is it going too far to 1) deduplicate the reference list, 2) merge all references to the same chapter into one list item, and 3) order the references in order of appearance?

**Comment by acabal** [comment]
Sure, that sounds like a positive change.
